<a href="https://colab.research.google.com/github/viddev1/tensorflow_notebooks/blob/main/IntroTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.8.0


In [ ]:
x = tf.constant(7)
print(x)

tf.Tensor(7, shape=(), dtype=int32)


In [ ]:
x.ndim

0

In [ ]:
vec = tf.constant([[[10,20],[10,20]],[[20,30],[20,30]]], dtype=tf.float16)
vec

<tf.Tensor: shape=(2, 2, 2), dtype=float16, numpy=
array([[[10., 20.],
        [10., 20.]],

       [[20., 30.],
        [20., 30.]]], dtype=float16)>

In [ ]:
vec.ndim

3

In [ ]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]], dtype=tf.float16, shape=(3,2,3) ,name="tens")
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=float16, numpy=
array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]],

       [[13., 14., 15.],
        [16., 17., 18.]]], dtype=float16)>

In [ ]:
tensor.ndim

3

In [ ]:
chg_tensor =  tf.Variable([1,3])
unchg_tensor = tf.constant([1,3])
chg_tensor, unchg_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 3], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>)

In [ ]:
chg_tensor[0].assign(7)
chg_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 3], dtype=int32)>

In [ ]:
#unchg_tensor[0].assign(7)
#unchg_tensor

In [ ]:
rand0 = tf.random.Generator.from_seed(0)
rand0 = rand0.normal(shape=(4,2))
rand1 = tf.random.Generator.from_seed(7)
rand1 = rand1.normal(shape=(4,2))
rand0, rand1, rand0 == rand1, rand1 == rand0

(<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[-1.3544159 ,  0.70454913],
        [ 0.03666191,  0.86918795],
        [ 0.43842277, -0.53439844],
        [-0.07710262,  1.5658046 ]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.2878567 ],
        [-0.8757901 , -0.08857017],
        [ 0.69211644,  0.84215707],
        [-0.06378496,  0.92800784]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False],
        [False, False]])>,
 <tf.Tensor: shape=(4, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False],
        [False, False]])>)

In [ ]:
tf.random.shuffle(rand0)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ 0.03666191,  0.86918795],
       [ 0.43842277, -0.53439844],
       [-1.3544159 ,  0.70454913],
       [-0.07710262,  1.5658046 ]], dtype=float32)>

In [ ]:
tf.random.shuffle(rand0, seed=21)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ 0.03666191,  0.86918795],
       [-1.3544159 ,  0.70454913],
       [-0.07710262,  1.5658046 ],
       [ 0.43842277, -0.53439844]], dtype=float32)>

In [ ]:
tf.ones(shape=(4,2))

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
import numpy as np
n_A = np.arange(0, 48, dtype= np.int32)
A = tf.constant(n_A, shape=[4,4,3])
n_A, A

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       dtype=int32), <tf.Tensor: shape=(4, 4, 3), dtype=int32, numpy=
 array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],
 
        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],
 
        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],
 
        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]]], dtype=int32)>)

In [ ]:
r4_tnsr = tf.zeros([2,3,4,5])
r4_tnsr

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
r4_tnsr.shape, r4_tnsr.ndim, tf.size(r4_tnsr)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of tensor
print("Datatype of every element:", r4_tnsr.dtype)
print("Number of dimensions (rank):", r4_tnsr.ndim)
print("Shape of tensor:", r4_tnsr.shape)
print("Elements along axis 0 of tensor:", r4_tnsr.shape[0])
print("Elements along last axis of tensor:", r4_tnsr.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(r4_tnsr).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


In [ ]:
r4_tnsr[:1, :3, :2, :4]

<tf.Tensor: shape=(1, 3, 2, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
r4_tnsr[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
r2_tnsr = tf.constant([[1,5],
                       [2,7]])
r2_tnsr[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 7], dtype=int32)>

In [ ]:
r3_tnsr = r2_tnsr[...,tf.newaxis]
r2_tnsr, r3_tnsr

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 5],
        [2, 7]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[1],
         [5]],
 
        [[2],
         [7]]], dtype=int32)>)

In [ ]:
tf.expand_dims(r2_tnsr, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [5]],

       [[2],
        [7]]], dtype=int32)>

In [ ]:
r2_tnsr+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 15],
       [12, 17]], dtype=int32)>

In [ ]:
r2_tnsr-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -5],
       [-8, -3]], dtype=int32)>

In [ ]:
r2_tnsr*5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 25],
       [10, 35]], dtype=int32)>

In [ ]:
tf.multiply(r2_tnsr, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 50],
       [20, 70]], dtype=int32)>

In [ ]:
print(r2_tnsr)
tf.matmul(r2_tnsr, r2_tnsr)

tf.Tensor(
[[1 5]
 [2 7]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 40],
       [16, 59]], dtype=int32)>

In [ ]:
r2_tnsr @ r2_tnsr

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 40],
       [16, 59]], dtype=int32)>

In [ ]:
# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
X@tf.transpose(Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
X@tf.reshape(Y, shape=[2,3])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.reshape(Y, shape=[2,3])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
tf.transpose(Y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]], dtype=int32)>

In [ ]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
Y.shape, tf.reshape(Y, (2, 3)).shape, tf.transpose(Y).shape, tf.transpose(X).shape

(TensorShape([3, 2]),
 TensorShape([2, 3]),
 TensorShape([2, 3]),
 TensorShape([2, 3]))

In [ ]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])

# Create a new tensor with default datatype (int32)
C = tf.constant([1, 7])
B, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [ ]:
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [ ]:
C = tf.cast(C, dtype=tf.int16)
C

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([1, 7], dtype=int16)>

In [ ]:
# Create tensor with negative values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
# Create a tensor with 50 random values between 0 and 100
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([45, 21, 79, 46, 67, 22, 89, 78, 76, 32, 33, 88, 15, 79,  7, 13, 35,
        2, 55, 29, 82, 74, 16,  4, 34, 40, 19, 44, 72, 56, 89, 36, 95,  0,
       70, 24, 44, 93, 34, 79, 25, 75, 88, 17, 16, 77, 35, 91, 62, 58])>

In [ ]:
tf.reduce_min(E),tf.reduce_max(E),tf.reduce_mean(E),tf.reduce_sum(E)

(<tf.Tensor: shape=(), dtype=int64, numpy=0>,
 <tf.Tensor: shape=(), dtype=int64, numpy=95>,
 <tf.Tensor: shape=(), dtype=int64, numpy=49>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2460>)

In [ ]:
# Create a tensor with 50 values between 0 and 1
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.56468661, 0.08130327, 0.73828207, 0.79387568, 0.27037611,
       0.17623642, 0.43281735, 0.30625919, 0.35971987, 0.15297854,
       0.36617998, 0.69800933, 0.95449182, 0.46370222, 0.70996242,
       0.98660048, 0.45463029, 0.6790863 , 0.74635369, 0.46232612,
       0.39788832, 0.55272621, 0.39141083, 0.98037107, 0.82005238,
       0.33110619, 0.85863748, 0.23220659, 0.04316528, 0.16013338,
       0.40834043, 0.68959542, 0.88662263, 0.83061173, 0.23946949,
       0.04377235, 0.82224226, 0.95827632, 0.94731828, 0.18742436,
       0.65769849, 0.14707712, 0.50207658, 0.52353446, 0.33241298,
       0.22605946, 0.61576237, 0.4603163 , 0.80726163, 0.30832905])>

In [ ]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=15>

In [ ]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=28>

In [ ]:
# Find the maximum element position of F
print(f"The maximum value of F is at position: {tf.argmax(F).numpy()}") 
print(f"The maximum value of F is: {tf.reduce_max(F).numpy()}") 
print(f"Using tf.argmax() to index F, the maximum value of F is: {F[tf.argmax(F)].numpy()}")
print(f"Are the two max values the same (they should be)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

The maximum value of F is at position: 15
The maximum value of F is: 0.986600482924704
Using tf.argmax() to index F, the maximum value of F is: 0.986600482924704
Are the two max values the same (they should be)? True


In [ ]:
G = tf.constant(np.random.randint(0, 100, 50), shape=(1,1,1,1,50))
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

In [ ]:
G, G_squeezed

(<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=int64, numpy=
 array([[[[[58, 50, 77, 43, 64, 45, 76, 93, 40, 97, 46, 39, 36,  9, 64,
            35, 52, 84, 20,  6, 86, 54, 55, 67,  2, 55, 47, 20,  2, 83,
            30, 91, 95, 52,  8, 32, 26, 88, 43, 24, 73, 83, 80, 54, 96,
            73, 52, 85, 81, 67]]]]])>,
 <tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([58, 50, 77, 43, 64, 45, 76, 93, 40, 97, 46, 39, 36,  9, 64, 35, 52,
        84, 20,  6, 86, 54, 55, 67,  2, 55, 47, 20,  2, 83, 30, 91, 95, 52,
         8, 32, 26, 88, 43, 24, 73, 83, 80, 54, 96, 73, 52, 85, 81, 67])>)

In [ ]:
lst = [0, 1, 2, 3] 

tf.one_hot(lst, depth=4, on_value=1, off_value=0)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)>

In [ ]:
H = tf.constant(np.arange(1, 10))
H

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [ ]:
tf.sqrt(
    tf.cast(H, dtype=tf.float32)
    )

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
tf.math.log(
     tf.cast(H, dtype=tf.float32)
)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [ ]:
# Create a variable tensor
I = tf.Variable(np.arange(0, 5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [ ]:
I.assign([0, 1, 2, 4, 50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  4, 50])>

In [ ]:
I.assign_add([10, 10, 10, 10, 10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 14, 60])>

In [ ]:
# Create a tensor from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# Create a tensor from NumPy and from an array
numpy_J = tf.constant(np.array([3., 7., 10.])) # will be float64 (due to NumPy)
tensor_J = tf.constant([3., 7., 10.]) # will be float32 (due to being TensorFlow default)
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

In [ ]:
# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [ ]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [ ]:
!nvidia-smi

Mon May 16 01:10:21 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P0    26W /  70W |    266MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------